---
development:
  cloud_name: oliver84
  api_key: '754552953449461'
  api_secret: VBkQww-tGkjDjwAPf7_l7RWRRwc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: oliver84
  api_key: '754552953449461'
  api_secret: VBkQww-tGkjDjwAPf7_l7RWRRwc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: oliver84
  api_key: '754552953449461'
  api_secret: VBkQww-tGkjDjwAPf7_l7RWRRwc
  enhance_image_tag: true
  static_image_support: false
